# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: reslver-kit
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
release:
  mode: append
  prerelease: auto
  header: |
    Those were the changes on {{ .Tag }}!
github_urls:
  api: https://git.k8s.app/api/v3/
  upload: https://git.k8s.app/api/uploads/
  download: https://git.k8s.app/
  # set to true if you use a self-signed certificate
  skip_tls_verify: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
